name: Test

on:
  push:
    branches:
      - main
      - feature/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Tidy
        run: go mod tidy
      - name: Test
        run: go test -v ./...
      - name: Run Demo
        run: go run main.go
      - name: Upload Test Artifact
        uses: actions/upload-artifact@v2
        with:
          name: proto-demo
          path: proto-demo
          if-no-files-found: error